x-notify-common: &notify-common
  image: notification-service:latest
  working_dir: /app/src
  env_file:
    - .env
  environment: &worker-environment
    PYTHONDONTWRITEBYTECODE: "1"
    PYTHONUNBUFFERED: "1"
#  volumes: &notify-volumes
#    - notify_uploads:/app/data/uploads
  depends_on:
    redis:
      condition: service_healthy
  restart: unless-stopped

services:
  api:
    <<: *notify-common
    build: .
    container_name: notify_api
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
#    expose:
#      - "8000"
    command: ["uv", "run", "python", "main.py"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
  postgres_db:
    image: postgres:18
    container_name: notify_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__POSTGRES__USER}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__POSTGRES__PASSWORD}"
      POSTGRES_DB: "${APP_CONFIG__DB__POSTGRES__DB}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_CONFIG__DB__POSTGRES__USER} -d ${APP_CONFIG__DB__POSTGRES__DB}" ]
      timeout: 5s
      interval: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql
  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Kyiv
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"


  smtp-worker:

    <<: *notify-common
    environment:
      <<: *worker-environment
      APP_CONFIG__SMTP__HOST: maildev
    depends_on:
      redis:
        condition: service_healthy
      maildev:
        condition: service_started
    command: [ "faststream", "run", "workers.smtp_worker:app" ]


  tg-worker:
    <<: *notify-common
    command: ["faststream", "run", "workers.tg_worker:app"]

  dlq-worker:
    <<: *notify-common
    command: ["faststream", "run", "workers.dlq_worker:app"]

  slack-worker:
    <<: *notify-common
    command: [ "faststream", "run", "workers.slack_worker:app" ]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  redis_data:
  postgres_data:
#  notify_uploads:
